DuydoFE/SWP391-HeroOut-FrontEnd

src/config/router.jsx, src/pages/ConsultantDetailPage.jsx
Create UI Consultant Detail Page
=> UI Consultant Detail Page

src/App.jsx, src/components/Header.jsx, src/components/ProtectedRoute.jsx, src/components/authentication/Login/Login.jsx, src/components/authentication/Register.jsx, src/config/router.jsx, src/contexts/AuthContext.jsx, src/services/axios.js, src/utils/jwtUtils.js
AuthContext and Authentication
=> AuthContext and Authentication

src/hooks/useApi.js, src/pages/BlogsPage.jsx, src/pages/BookingPage.jsx, src/pages/ConsultationPage.jsx, src/services/apiService.js
=> Hooks and ApiService

src/pages/BookingPage.jsx
Auto fill member info from API
=> Auto fill member info from API

src/App.jsx, src/components/authentication/Login/Login.jsx, src/components/authentication/Register.jsx, src/contexts/AuthContext.jsx
Update notification when login and register
=> Update notification when login and register

src/pages/ProfilePage.jsx, src/services/apiService.js
=> fix bug update profile

src/config/router.jsx
Delete event register in router
=> Delete event register in router

src/components/layout/StaffLayout.jsx, src/components/staff/StaffBlog.jsx, src/config/router.jsx
=> Update Sidebar Dashboard

src/components/MemberProtectedRoute.jsx, src/components/ProtectedRoute.jsx, src/components/authentication/Login/Login.jsx, src/config/router.jsx
Assign access rights to each role
=> Assign access rights to each role

src/components/staff/StaffBlog.jsx
=> UI Staff Blogs

src/components/staff/StaffDashBoard.jsx, src/services/apiService.js
=> Update UI Staff Dashboard

src/services/apiService.js
=> Update call API from backend

src/pages/BookingPage.jsx, src/services/apiService.js
Format time and new apiService
=> Format time and new apiService

src/config/router.jsx, src/pages/MyAppointmentsPage.jsx
=> UI My appointments page

src/pages/BookingPage.jsx
Update api, format time, and form for booking page
=> Update api, format time, and form for booking page

src/components/staff/StaffMeeting.jsx
Update call api and UI for staff meeting
=> Update call api and UI for staff meeting

src/components/staff/StaffBlog.jsx, src/pages/BlogDetailPage.jsx
=> Call Api Blogs

src/store/redux/features/counterSlice.js, src/store/redux/rootReducer.js, src/store/redux/store.js
=> fixbug store

src/pages/BookingPage.jsx, src/pages/ConsultantDetailPage.jsx, src/pages/MyAppointmentsPage.jsx
Hide past schedules and past slots
=> Hide past schedules and past slots

src/components/Header.jsx, src/contexts/AuthContext.jsx, src/pages/ProfilePage.jsx
Show avatar on Header and Menu dropdown
=> Show avatar on Header and Menu dropdown

src/components/staff/StaffMeeting.jsx
Auto-cancel expired appointments for StaffMeeting
=> Auto-cancel expired appointments for StaffMeeting

src/services/apiService.js
Hide consultant account inactive
=> Hide consultant account inactive

src/components/staff/StaffMember.jsx, src/services/apiService.js
Update information for consultant
=> Update information for consultant
